version: '3'
services:
  nestjs:
    build: .
    ports:
      - '${NEST_PORT}:${NEST_PORT}'
    depends_on:
      - postgres
    env_file:
      - .env
    restart: always
  postgres:
    image: postgres
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    env_file:
      - .env
